# Generated by Django 3.2.9 on 2022-02-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211128_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ALL', 'all'), ('RESIDENTIAL', 'residential'), ('OFFICE', 'office'), ('COMMERCIAL', 'commercial'), ('HOSPITALITY', 'hospitality'), ('EXHIBITION', 'exhibition'), ('FURNITURE', 'furniture'), ('UNBUILT', 'unbuilt'), ('ETC', 'etc')], max_length=32),
        ),
    ]
