# Generated by Django 3.2.9 on 2022-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('residential', 'residential'), ('office', 'office'), ('commercial', 'commercial'), ('hospitality', 'hospitality'), ('exhibition', 'exhibition'), ('furniture', 'furniture'), ('unbuilt', 'unbuilt'), ('etc', 'etc')], max_length=32),
        ),
    ]
