# Generated by Django 3.2.9 on 2022-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_date',
            field=models.DateField(blank=True, default='2020-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='to_date',
            field=models.DateField(blank=True, default='2020-02-02'),
            preserve_default=False,
        ),
    ]
