# Generated by Django 3.2.9 on 2022-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220405_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='asdfasdf', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sudtitle',
            field=models.CharField(default='asdfasdf', max_length=256),
            preserve_default=False,
        ),
    ]
