# Generated by Django 3.2.9 on 2022-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_list',
            field=models.TextField(blank=True),
        ),
    ]
